name: LEX Sniper Userbot

on:
  schedule:
    - cron: '0 */4 * * *' # Резервный запуск каждые 4 часа
  workflow_dispatch:

concurrency:
  group: telegram-userbot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install System Packages (FFmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon rlottie-python pillow opencv-python-headless numpy requests pilmoji

      - name: Run Userbot with Auto-Relay
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          timeout 20400s python app.py || true

          echo "⏳ Время смены караула (5ч 40м вышло). Запускаем следующий цикл..."
          gh workflow run "LEX Sniper Userbot" --ref main
